//! Mapping helpers between logical `sevai` request or response types and wire
//! protobuf envelopes generated by Buffa.
//!
//! The TCP transport decodes protobuf bytes into zero-copy Buffa views, then
//! calls this module to produce the existing logical server API types.

use crate::error::KalanjiyamError;
use crate::pezhai::types::{
    Bound, GetResponse, LevelStats, LogicalShardStats, ScanRow, StatsResponse, SyncResponse,
};
use crate::sevai::generated as wire;
use crate::sevai::{
    ExternalMethod, ExternalRequest, ExternalResponse, ExternalResponsePayload,
    ScanFetchNextResponse, ScanStartResponse, Status, StatusCode,
};

/// Converts one logical external request to its protobuf wire envelope.
#[must_use]
pub fn request_to_wire(request: &ExternalRequest) -> wire::RequestEnvelope {
    let method = match &request.method {
        ExternalMethod::Put { key, value } => Some(wire::request_envelope::Method::Put(Box::new(
            wire::PutRequest {
                key: key.clone(),
                value: value.clone(),
                ..Default::default()
            },
        ))),
        ExternalMethod::Delete { key } => Some(wire::request_envelope::Method::Delete(Box::new(
            wire::DeleteRequest {
                key: key.clone(),
                ..Default::default()
            },
        ))),
        ExternalMethod::Get { key } => Some(wire::request_envelope::Method::Get(Box::new(
            wire::GetRequest {
                key: key.clone(),
                ..Default::default()
            },
        ))),
        ExternalMethod::ScanStart {
            start_bound,
            end_bound,
            max_records_per_page,
            max_bytes_per_page,
        } => Some(wire::request_envelope::Method::ScanStart(Box::new(
            wire::ScanStartRequest {
                start_bound: bound_to_wire(start_bound).into(),
                end_bound: bound_to_wire(end_bound).into(),
                max_records_per_page: *max_records_per_page,
                max_bytes_per_page: *max_bytes_per_page,
                ..Default::default()
            },
        ))),
        ExternalMethod::ScanFetchNext { scan_id } => Some(
            wire::request_envelope::Method::ScanFetchNext(Box::new(wire::ScanFetchNextRequest {
                scan_id: *scan_id,
                ..Default::default()
            })),
        ),
        ExternalMethod::Sync => Some(wire::request_envelope::Method::Sync(Box::default())),
        ExternalMethod::Stats => Some(wire::request_envelope::Method::Stats(Box::default())),
    };

    wire::RequestEnvelope {
        client_id: request.client_id.clone(),
        request_id: request.request_id,
        cancel_token: request.cancel_token.clone(),
        method,
        ..Default::default()
    }
}

/// Converts one owned protobuf wire request to a logical external request.
pub fn request_from_wire(
    request: &wire::RequestEnvelope,
) -> Result<ExternalRequest, KalanjiyamError> {
    let method = request
        .method
        .as_ref()
        .ok_or_else(|| invalid_wire("request is missing method"))?;

    let method = match method {
        wire::request_envelope::Method::Put(payload) => ExternalMethod::Put {
            key: payload.key.clone(),
            value: payload.value.clone(),
        },
        wire::request_envelope::Method::Delete(payload) => ExternalMethod::Delete {
            key: payload.key.clone(),
        },
        wire::request_envelope::Method::Get(payload) => ExternalMethod::Get {
            key: payload.key.clone(),
        },
        wire::request_envelope::Method::ScanStart(payload) => ExternalMethod::ScanStart {
            start_bound: bound_from_wire(
                payload
                    .start_bound
                    .as_option()
                    .ok_or_else(|| invalid_wire("scan_start.start_bound is required"))?,
            )?,
            end_bound: bound_from_wire(
                payload
                    .end_bound
                    .as_option()
                    .ok_or_else(|| invalid_wire("scan_start.end_bound is required"))?,
            )?,
            max_records_per_page: payload.max_records_per_page,
            max_bytes_per_page: payload.max_bytes_per_page,
        },
        wire::request_envelope::Method::ScanFetchNext(payload) => ExternalMethod::ScanFetchNext {
            scan_id: payload.scan_id,
        },
        wire::request_envelope::Method::Sync(_) => ExternalMethod::Sync,
        wire::request_envelope::Method::Stats(_) => ExternalMethod::Stats,
    };

    Ok(ExternalRequest {
        client_id: request.client_id.clone(),
        request_id: request.request_id,
        method,
        cancel_token: request.cancel_token.clone(),
    })
}

/// Converts one zero-copy protobuf wire request view to a logical request.
pub fn request_from_wire_view(
    request: &wire::RequestEnvelopeView<'_>,
) -> Result<ExternalRequest, KalanjiyamError> {
    let method = request
        .method
        .as_ref()
        .ok_or_else(|| invalid_wire("request view is missing method"))?;

    let method = match method {
        wire::request_envelope::MethodView::Put(payload) => ExternalMethod::Put {
            key: payload.key.to_vec(),
            value: payload.value.to_vec(),
        },
        wire::request_envelope::MethodView::Delete(payload) => ExternalMethod::Delete {
            key: payload.key.to_vec(),
        },
        wire::request_envelope::MethodView::Get(payload) => ExternalMethod::Get {
            key: payload.key.to_vec(),
        },
        wire::request_envelope::MethodView::ScanStart(payload) => ExternalMethod::ScanStart {
            start_bound: bound_from_wire_view(
                payload
                    .start_bound
                    .as_option()
                    .ok_or_else(|| invalid_wire("scan_start.start_bound is required"))?,
            )?,
            end_bound: bound_from_wire_view(
                payload
                    .end_bound
                    .as_option()
                    .ok_or_else(|| invalid_wire("scan_start.end_bound is required"))?,
            )?,
            max_records_per_page: payload.max_records_per_page,
            max_bytes_per_page: payload.max_bytes_per_page,
        },
        wire::request_envelope::MethodView::ScanFetchNext(payload) => {
            ExternalMethod::ScanFetchNext {
                scan_id: payload.scan_id,
            }
        }
        wire::request_envelope::MethodView::Sync(_) => ExternalMethod::Sync,
        wire::request_envelope::MethodView::Stats(_) => ExternalMethod::Stats,
    };

    Ok(ExternalRequest {
        client_id: request.client_id.to_string(),
        request_id: request.request_id,
        method,
        cancel_token: request.cancel_token.map(std::string::ToString::to_string),
    })
}

/// Converts one logical external response to its protobuf wire envelope.
#[must_use]
pub fn response_to_wire(response: &ExternalResponse) -> wire::ResponseEnvelope {
    let payload = match &response.payload {
        None => None,
        Some(ExternalResponsePayload::Put) => {
            Some(wire::response_envelope::Payload::Put(Box::default()))
        }
        Some(ExternalResponsePayload::Delete) => {
            Some(wire::response_envelope::Payload::Delete(Box::default()))
        }
        Some(ExternalResponsePayload::Get(payload)) => Some(wire::response_envelope::Payload::Get(
            Box::new(wire::GetResponse {
                found: payload.found,
                value: payload.value.clone(),
                observation_seqno: payload.observation_seqno,
                data_generation: payload.data_generation,
                ..Default::default()
            }),
        )),
        Some(ExternalResponsePayload::ScanStart(payload)) => Some(
            wire::response_envelope::Payload::ScanStart(Box::new(wire::ScanStartResponse {
                scan_id: payload.scan_id,
                observation_seqno: payload.observation_seqno,
                data_generation: payload.data_generation,
                ..Default::default()
            })),
        ),
        Some(ExternalResponsePayload::ScanFetchNext(payload)) => {
            Some(wire::response_envelope::Payload::ScanFetchNext(Box::new(
                wire::ScanFetchNextResponse {
                    rows: payload.rows.iter().map(scan_row_to_wire).collect(),
                    eof: payload.eof,
                    ..Default::default()
                },
            )))
        }
        Some(ExternalResponsePayload::Sync(payload)) => Some(
            wire::response_envelope::Payload::Sync(Box::new(wire::SyncResponse {
                durable_seqno: payload.durable_seqno,
                ..Default::default()
            })),
        ),
        Some(ExternalResponsePayload::Stats(payload)) => Some(
            wire::response_envelope::Payload::Stats(Box::new(stats_response_to_wire(payload))),
        ),
    };

    wire::ResponseEnvelope {
        client_id: response.client_id.clone(),
        request_id: response.request_id,
        status: status_to_wire(&response.status).into(),
        payload,
        ..Default::default()
    }
}

/// Converts one owned protobuf wire response to a logical external response.
pub fn response_from_wire(
    response: &wire::ResponseEnvelope,
) -> Result<ExternalResponse, KalanjiyamError> {
    let status = status_from_wire(
        response
            .status
            .as_option()
            .ok_or_else(|| invalid_wire("response is missing status"))?,
    )?;
    let payload = payload_from_wire(response.payload.as_ref())?;
    Ok(ExternalResponse {
        client_id: response.client_id.clone(),
        request_id: response.request_id,
        status,
        payload,
    })
}

/// Converts one zero-copy protobuf wire response view to a logical response.
pub fn response_from_wire_view(
    response: &wire::ResponseEnvelopeView<'_>,
) -> Result<ExternalResponse, KalanjiyamError> {
    let status = status_from_wire_view(
        response
            .status
            .as_option()
            .ok_or_else(|| invalid_wire("response view is missing status"))?,
    )?;
    let payload = payload_from_wire_view(response.payload.as_ref())?;
    Ok(ExternalResponse {
        client_id: response.client_id.to_string(),
        request_id: response.request_id,
        status,
        payload,
    })
}

fn payload_from_wire(
    payload: Option<&wire::response_envelope::Payload>,
) -> Result<Option<ExternalResponsePayload>, KalanjiyamError> {
    match payload {
        None => Ok(None),
        Some(wire::response_envelope::Payload::Put(_)) => Ok(Some(ExternalResponsePayload::Put)),
        Some(wire::response_envelope::Payload::Delete(_)) => {
            Ok(Some(ExternalResponsePayload::Delete))
        }
        Some(wire::response_envelope::Payload::Get(payload)) => {
            Ok(Some(ExternalResponsePayload::Get(GetResponse {
                found: payload.found,
                value: payload.value.clone(),
                observation_seqno: payload.observation_seqno,
                data_generation: payload.data_generation,
            })))
        }
        Some(wire::response_envelope::Payload::ScanStart(payload)) => Ok(Some(
            ExternalResponsePayload::ScanStart(ScanStartResponse {
                scan_id: payload.scan_id,
                observation_seqno: payload.observation_seqno,
                data_generation: payload.data_generation,
            }),
        )),
        Some(wire::response_envelope::Payload::ScanFetchNext(payload)) => Ok(Some(
            ExternalResponsePayload::ScanFetchNext(ScanFetchNextResponse {
                rows: payload.rows.iter().map(scan_row_from_wire).collect(),
                eof: payload.eof,
            }),
        )),
        Some(wire::response_envelope::Payload::Sync(payload)) => {
            Ok(Some(ExternalResponsePayload::Sync(SyncResponse {
                durable_seqno: payload.durable_seqno,
            })))
        }
        Some(wire::response_envelope::Payload::Stats(payload)) => Ok(Some(
            ExternalResponsePayload::Stats(stats_response_from_wire(payload)?),
        )),
    }
}

fn payload_from_wire_view(
    payload: Option<&wire::response_envelope::PayloadView<'_>>,
) -> Result<Option<ExternalResponsePayload>, KalanjiyamError> {
    match payload {
        None => Ok(None),
        Some(wire::response_envelope::PayloadView::Put(_)) => {
            Ok(Some(ExternalResponsePayload::Put))
        }
        Some(wire::response_envelope::PayloadView::Delete(_)) => {
            Ok(Some(ExternalResponsePayload::Delete))
        }
        Some(wire::response_envelope::PayloadView::Get(payload)) => {
            Ok(Some(ExternalResponsePayload::Get(GetResponse {
                found: payload.found,
                value: payload.value.map(|value| value.to_vec()),
                observation_seqno: payload.observation_seqno,
                data_generation: payload.data_generation,
            })))
        }
        Some(wire::response_envelope::PayloadView::ScanStart(payload)) => Ok(Some(
            ExternalResponsePayload::ScanStart(ScanStartResponse {
                scan_id: payload.scan_id,
                observation_seqno: payload.observation_seqno,
                data_generation: payload.data_generation,
            }),
        )),
        Some(wire::response_envelope::PayloadView::ScanFetchNext(payload)) => Ok(Some(
            ExternalResponsePayload::ScanFetchNext(ScanFetchNextResponse {
                rows: payload.rows.iter().map(scan_row_from_wire_view).collect(),
                eof: payload.eof,
            }),
        )),
        Some(wire::response_envelope::PayloadView::Sync(payload)) => {
            Ok(Some(ExternalResponsePayload::Sync(SyncResponse {
                durable_seqno: payload.durable_seqno,
            })))
        }
        Some(wire::response_envelope::PayloadView::Stats(payload)) => Ok(Some(
            ExternalResponsePayload::Stats(stats_response_from_wire_view(payload)?),
        )),
    }
}

fn status_to_wire(status: &Status) -> wire::Status {
    wire::Status {
        code: wire_status_code_from_domain(status.code).into(),
        retryable: status.retryable,
        message: status.message.clone(),
        ..Default::default()
    }
}

fn status_from_wire(status: &wire::Status) -> Result<Status, KalanjiyamError> {
    Ok(Status {
        code: domain_status_code_from_wire(status.code)?,
        retryable: status.retryable,
        message: status.message.clone(),
    })
}

fn status_from_wire_view(status: &wire::StatusView<'_>) -> Result<Status, KalanjiyamError> {
    Ok(Status {
        code: domain_status_code_from_wire(status.code)?,
        retryable: status.retryable,
        message: status.message.map(std::string::ToString::to_string),
    })
}

fn wire_status_code_from_domain(code: StatusCode) -> wire::StatusCode {
    match code {
        StatusCode::Ok => wire::StatusCode::STATUS_CODE_OK,
        StatusCode::Busy => wire::StatusCode::STATUS_CODE_BUSY,
        StatusCode::InvalidArgument => wire::StatusCode::STATUS_CODE_INVALID_ARGUMENT,
        StatusCode::Io => wire::StatusCode::STATUS_CODE_IO,
        StatusCode::Checksum => wire::StatusCode::STATUS_CODE_CHECKSUM,
        StatusCode::Corruption => wire::StatusCode::STATUS_CODE_CORRUPTION,
        StatusCode::Stale => wire::StatusCode::STATUS_CODE_STALE,
        StatusCode::Cancelled => wire::StatusCode::STATUS_CODE_CANCELLED,
    }
}

fn domain_status_code_from_wire(
    code: ::buffa::EnumValue<wire::StatusCode>,
) -> Result<StatusCode, KalanjiyamError> {
    let known = code
        .as_known()
        .ok_or_else(|| invalid_wire(format!("unknown status code {}", code.to_i32())))?;
    match known {
        wire::StatusCode::STATUS_CODE_OK => Ok(StatusCode::Ok),
        wire::StatusCode::STATUS_CODE_BUSY => Ok(StatusCode::Busy),
        wire::StatusCode::STATUS_CODE_INVALID_ARGUMENT => Ok(StatusCode::InvalidArgument),
        wire::StatusCode::STATUS_CODE_IO => Ok(StatusCode::Io),
        wire::StatusCode::STATUS_CODE_CHECKSUM => Ok(StatusCode::Checksum),
        wire::StatusCode::STATUS_CODE_CORRUPTION => Ok(StatusCode::Corruption),
        wire::StatusCode::STATUS_CODE_STALE => Ok(StatusCode::Stale),
        wire::StatusCode::STATUS_CODE_CANCELLED => Ok(StatusCode::Cancelled),
        wire::StatusCode::STATUS_CODE_UNSPECIFIED => Err(invalid_wire(
            "status code STATUS_CODE_UNSPECIFIED is not valid",
        )),
    }
}

fn bound_to_wire(bound: &Bound) -> wire::Bound {
    let kind = match bound {
        Bound::Finite(key) => wire::bound::Kind::Finite(key.clone()),
        Bound::NegInf => wire::bound::Kind::NegInf(Box::default()),
        Bound::PosInf => wire::bound::Kind::PosInf(Box::default()),
    };
    wire::Bound {
        kind: Some(kind),
        ..Default::default()
    }
}

fn bound_from_wire(bound: &wire::Bound) -> Result<Bound, KalanjiyamError> {
    let kind = bound
        .kind
        .as_ref()
        .ok_or_else(|| invalid_wire("bound is missing kind"))?;
    match kind {
        wire::bound::Kind::Finite(key) => Ok(Bound::Finite(key.clone())),
        wire::bound::Kind::NegInf(_) => Ok(Bound::NegInf),
        wire::bound::Kind::PosInf(_) => Ok(Bound::PosInf),
    }
}

fn bound_from_wire_view(bound: &wire::BoundView<'_>) -> Result<Bound, KalanjiyamError> {
    let kind = bound
        .kind
        .as_ref()
        .ok_or_else(|| invalid_wire("bound view is missing kind"))?;
    match kind {
        wire::bound::KindView::Finite(key) => Ok(Bound::Finite(key.to_vec())),
        wire::bound::KindView::NegInf(_) => Ok(Bound::NegInf),
        wire::bound::KindView::PosInf(_) => Ok(Bound::PosInf),
    }
}

fn scan_row_to_wire(row: &ScanRow) -> wire::ScanRow {
    wire::ScanRow {
        key: row.key.clone(),
        value: row.value.clone(),
        ..Default::default()
    }
}

fn scan_row_from_wire(row: &wire::ScanRow) -> ScanRow {
    ScanRow {
        key: row.key.clone(),
        value: row.value.clone(),
    }
}

fn scan_row_from_wire_view(row: &wire::ScanRowView<'_>) -> ScanRow {
    ScanRow {
        key: row.key.to_vec(),
        value: row.value.to_vec(),
    }
}

fn stats_response_to_wire(stats: &StatsResponse) -> wire::StatsResponse {
    wire::StatsResponse {
        observation_seqno: stats.observation_seqno,
        data_generation: stats.data_generation,
        levels: stats.levels.iter().map(level_stats_to_wire).collect(),
        logical_shards: stats
            .logical_shards
            .iter()
            .map(logical_shard_stats_to_wire)
            .collect(),
        ..Default::default()
    }
}

fn stats_response_from_wire(stats: &wire::StatsResponse) -> Result<StatsResponse, KalanjiyamError> {
    Ok(StatsResponse {
        observation_seqno: stats.observation_seqno,
        data_generation: stats.data_generation,
        levels: stats
            .levels
            .iter()
            .map(level_stats_from_wire)
            .collect::<Result<Vec<_>, _>>()?,
        logical_shards: stats
            .logical_shards
            .iter()
            .map(logical_shard_stats_from_wire)
            .collect::<Result<Vec<_>, _>>()?,
    })
}

fn stats_response_from_wire_view(
    stats: &wire::StatsResponseView<'_>,
) -> Result<StatsResponse, KalanjiyamError> {
    Ok(StatsResponse {
        observation_seqno: stats.observation_seqno,
        data_generation: stats.data_generation,
        levels: stats
            .levels
            .iter()
            .map(level_stats_from_wire_view)
            .collect::<Result<Vec<_>, _>>()?,
        logical_shards: stats
            .logical_shards
            .iter()
            .map(logical_shard_stats_from_wire_view)
            .collect::<Result<Vec<_>, _>>()?,
    })
}

fn level_stats_to_wire(stats: &LevelStats) -> wire::LevelStats {
    wire::LevelStats {
        level_no: u32::from(stats.level_no),
        file_count: stats.file_count,
        logical_bytes: stats.logical_bytes,
        physical_bytes: stats.physical_bytes,
        ..Default::default()
    }
}

fn level_stats_from_wire(stats: &wire::LevelStats) -> Result<LevelStats, KalanjiyamError> {
    let level_no = u16::try_from(stats.level_no).map_err(|_| {
        invalid_wire(format!(
            "level_stats.level_no {} exceeds u16 range",
            stats.level_no
        ))
    })?;
    Ok(LevelStats {
        level_no,
        file_count: stats.file_count,
        logical_bytes: stats.logical_bytes,
        physical_bytes: stats.physical_bytes,
    })
}

fn level_stats_from_wire_view(
    stats: &wire::LevelStatsView<'_>,
) -> Result<LevelStats, KalanjiyamError> {
    let level_no = u16::try_from(stats.level_no).map_err(|_| {
        invalid_wire(format!(
            "level_stats.level_no {} exceeds u16 range",
            stats.level_no
        ))
    })?;
    Ok(LevelStats {
        level_no,
        file_count: stats.file_count,
        logical_bytes: stats.logical_bytes,
        physical_bytes: stats.physical_bytes,
    })
}

fn logical_shard_stats_to_wire(stats: &LogicalShardStats) -> wire::LogicalShardStats {
    wire::LogicalShardStats {
        start_bound: bound_to_wire(&stats.start_bound).into(),
        end_bound: bound_to_wire(&stats.end_bound).into(),
        live_size_bytes: stats.live_size_bytes,
        ..Default::default()
    }
}

fn logical_shard_stats_from_wire(
    stats: &wire::LogicalShardStats,
) -> Result<LogicalShardStats, KalanjiyamError> {
    Ok(LogicalShardStats {
        start_bound: bound_from_wire(
            stats
                .start_bound
                .as_option()
                .ok_or_else(|| invalid_wire("logical_shard_stats.start_bound is required"))?,
        )?,
        end_bound: bound_from_wire(
            stats
                .end_bound
                .as_option()
                .ok_or_else(|| invalid_wire("logical_shard_stats.end_bound is required"))?,
        )?,
        live_size_bytes: stats.live_size_bytes,
    })
}

fn logical_shard_stats_from_wire_view(
    stats: &wire::LogicalShardStatsView<'_>,
) -> Result<LogicalShardStats, KalanjiyamError> {
    Ok(LogicalShardStats {
        start_bound: bound_from_wire_view(
            stats
                .start_bound
                .as_option()
                .ok_or_else(|| invalid_wire("logical_shard_stats.start_bound is required"))?,
        )?,
        end_bound: bound_from_wire_view(
            stats
                .end_bound
                .as_option()
                .ok_or_else(|| invalid_wire("logical_shard_stats.end_bound is required"))?,
        )?,
        live_size_bytes: stats.live_size_bytes,
    })
}

fn invalid_wire(message: impl Into<String>) -> KalanjiyamError {
    KalanjiyamError::InvalidArgument(message.into())
}

#[cfg(test)]
mod tests {
    use super::*;
    use buffa::{Message, MessageView};

    fn all_statuses() -> Vec<Status> {
        vec![
            Status {
                code: StatusCode::Ok,
                retryable: false,
                message: None,
            },
            Status {
                code: StatusCode::Busy,
                retryable: true,
                message: Some("busy".to_string()),
            },
            Status {
                code: StatusCode::InvalidArgument,
                retryable: false,
                message: Some("invalid".to_string()),
            },
            Status {
                code: StatusCode::Io,
                retryable: true,
                message: Some("io".to_string()),
            },
            Status {
                code: StatusCode::Checksum,
                retryable: false,
                message: Some("checksum".to_string()),
            },
            Status {
                code: StatusCode::Corruption,
                retryable: false,
                message: Some("corruption".to_string()),
            },
            Status {
                code: StatusCode::Stale,
                retryable: false,
                message: Some("stale".to_string()),
            },
            Status {
                code: StatusCode::Cancelled,
                retryable: true,
                message: Some("cancelled".to_string()),
            },
        ]
    }

    fn scan_rows() -> Vec<ScanRow> {
        vec![
            ScanRow {
                key: b"ant".to_vec(),
                value: b"v1".to_vec(),
            },
            ScanRow {
                key: b"bee".to_vec(),
                value: b"v2".to_vec(),
            },
        ]
    }

    #[test]
    fn bound_roundtrip_covers_all_variants() {
        for bound in [Bound::Finite(b"yak".to_vec()), Bound::NegInf, Bound::PosInf] {
            let wire = bound_to_wire(&bound);
            let owned = bound_from_wire(&wire).expect("owned bound decode should succeed");
            assert_eq!(owned, bound);

            let encoded = wire.encode_to_vec();
            let view = wire::BoundView::decode_view(&encoded)
                .expect("bound view decode should succeed for encoded wire message");
            let from_view = bound_from_wire_view(&view).expect("bound view mapping should succeed");
            assert_eq!(from_view, bound);
        }
    }

    #[test]
    fn status_roundtrip_covers_all_variants() {
        for status in all_statuses() {
            let wire = status_to_wire(&status);
            let owned = status_from_wire(&wire).expect("owned status decode should succeed");
            assert_eq!(owned, status);

            let encoded = wire.encode_to_vec();
            let view = wire::StatusView::decode_view(&encoded)
                .expect("status view decode should succeed for encoded wire message");
            let from_view =
                status_from_wire_view(&view).expect("status view mapping should succeed");
            assert_eq!(from_view, status);
        }
    }

    #[test]
    fn request_roundtrip_covers_all_method_variants() {
        let requests = vec![
            ExternalRequest {
                client_id: "c1".to_string(),
                request_id: 1,
                method: ExternalMethod::Put {
                    key: b"ant".to_vec(),
                    value: b"value".to_vec(),
                },
                cancel_token: Some("tok-a".to_string()),
            },
            ExternalRequest {
                client_id: "c1".to_string(),
                request_id: 2,
                method: ExternalMethod::Delete {
                    key: b"bee".to_vec(),
                },
                cancel_token: None,
            },
            ExternalRequest {
                client_id: "c1".to_string(),
                request_id: 3,
                method: ExternalMethod::Get {
                    key: b"cat".to_vec(),
                },
                cancel_token: None,
            },
            ExternalRequest {
                client_id: "c1".to_string(),
                request_id: 4,
                method: ExternalMethod::ScanStart {
                    start_bound: Bound::NegInf,
                    end_bound: Bound::Finite(b"yak".to_vec()),
                    max_records_per_page: 128,
                    max_bytes_per_page: 262_144,
                },
                cancel_token: Some("tok-b".to_string()),
            },
            ExternalRequest {
                client_id: "c1".to_string(),
                request_id: 5,
                method: ExternalMethod::ScanFetchNext { scan_id: 44 },
                cancel_token: None,
            },
            ExternalRequest {
                client_id: "c1".to_string(),
                request_id: 6,
                method: ExternalMethod::Sync,
                cancel_token: None,
            },
            ExternalRequest {
                client_id: "c1".to_string(),
                request_id: 7,
                method: ExternalMethod::Stats,
                cancel_token: None,
            },
        ];

        for request in requests {
            let wire = request_to_wire(&request);
            let owned = request_from_wire(&wire).expect("owned request mapping should succeed");
            assert_eq!(owned, request);

            let encoded = wire.encode_to_vec();
            let view = wire::RequestEnvelopeView::decode_view(&encoded)
                .expect("request view decode should succeed for encoded wire message");
            let from_view =
                request_from_wire_view(&view).expect("request view mapping should succeed");
            assert_eq!(from_view, request);
        }
    }

    #[test]
    fn response_roundtrip_covers_all_status_and_payload_variants() {
        let mut responses = Vec::new();

        for (index, status) in all_statuses().into_iter().enumerate() {
            responses.push(ExternalResponse {
                client_id: "c2".to_string(),
                request_id: index as u64 + 1,
                status,
                payload: None,
            });
        }

        responses.extend([
            ExternalResponse {
                client_id: "c2".to_string(),
                request_id: 100,
                status: Status::ok(),
                payload: Some(ExternalResponsePayload::Put),
            },
            ExternalResponse {
                client_id: "c2".to_string(),
                request_id: 101,
                status: Status::ok(),
                payload: Some(ExternalResponsePayload::Delete),
            },
            ExternalResponse {
                client_id: "c2".to_string(),
                request_id: 102,
                status: Status::ok(),
                payload: Some(ExternalResponsePayload::Get(GetResponse {
                    found: true,
                    value: Some(Vec::new()),
                    observation_seqno: 10,
                    data_generation: 3,
                })),
            },
            ExternalResponse {
                client_id: "c2".to_string(),
                request_id: 103,
                status: Status::ok(),
                payload: Some(ExternalResponsePayload::ScanStart(ScanStartResponse {
                    scan_id: 12,
                    observation_seqno: 13,
                    data_generation: 14,
                })),
            },
            ExternalResponse {
                client_id: "c2".to_string(),
                request_id: 104,
                status: Status::ok(),
                payload: Some(ExternalResponsePayload::ScanFetchNext(
                    ScanFetchNextResponse {
                        rows: scan_rows(),
                        eof: false,
                    },
                )),
            },
            ExternalResponse {
                client_id: "c2".to_string(),
                request_id: 105,
                status: Status::ok(),
                payload: Some(ExternalResponsePayload::Sync(SyncResponse {
                    durable_seqno: 55,
                })),
            },
            ExternalResponse {
                client_id: "c2".to_string(),
                request_id: 106,
                status: Status::ok(),
                payload: Some(ExternalResponsePayload::Stats(StatsResponse {
                    observation_seqno: 99,
                    data_generation: 7,
                    levels: vec![LevelStats {
                        level_no: 4,
                        file_count: 11,
                        logical_bytes: 22,
                        physical_bytes: 33,
                    }],
                    logical_shards: vec![LogicalShardStats {
                        start_bound: Bound::Finite(b"ant".to_vec()),
                        end_bound: Bound::PosInf,
                        live_size_bytes: 44,
                    }],
                })),
            },
        ]);

        for response in responses {
            let wire = response_to_wire(&response);
            let owned = response_from_wire(&wire).expect("owned response mapping should succeed");
            assert_eq!(owned, response);

            let encoded = wire.encode_to_vec();
            let view = wire::ResponseEnvelopeView::decode_view(&encoded)
                .expect("response view decode should succeed for encoded wire message");
            let from_view =
                response_from_wire_view(&view).expect("response view mapping should succeed");
            assert_eq!(from_view, response);
        }
    }

    #[test]
    fn missing_request_method_and_missing_scan_bounds_are_rejected() {
        let request_without_method = wire::RequestEnvelope {
            client_id: "c3".to_string(),
            request_id: 1,
            ..Default::default()
        };
        let error = request_from_wire(&request_without_method)
            .expect_err("request mapping should reject missing method");
        assert!(matches!(error, KalanjiyamError::InvalidArgument(_)));

        let scan_without_bounds = wire::RequestEnvelope {
            client_id: "c3".to_string(),
            request_id: 2,
            method: Some(wire::request_envelope::Method::ScanStart(Box::new(
                wire::ScanStartRequest::default(),
            ))),
            ..Default::default()
        };
        let error = request_from_wire(&scan_without_bounds)
            .expect_err("request mapping should reject missing scan bounds");
        assert!(matches!(error, KalanjiyamError::InvalidArgument(_)));

        let encoded = scan_without_bounds.encode_to_vec();
        let view = wire::RequestEnvelopeView::decode_view(&encoded)
            .expect("request view decode should succeed for malformed logical payload");
        let error = request_from_wire_view(&view)
            .expect_err("request view mapping should reject missing scan bounds");
        assert!(matches!(error, KalanjiyamError::InvalidArgument(_)));
    }

    #[test]
    fn missing_response_status_and_unknown_status_code_are_rejected() {
        let response_without_status = wire::ResponseEnvelope {
            client_id: "c4".to_string(),
            request_id: 1,
            ..Default::default()
        };
        let error = response_from_wire(&response_without_status)
            .expect_err("response mapping should reject missing status");
        assert!(matches!(error, KalanjiyamError::InvalidArgument(_)));

        let response_unknown_status = wire::ResponseEnvelope {
            client_id: "c4".to_string(),
            request_id: 2,
            status: wire::Status {
                code: 777.into(),
                retryable: true,
                message: Some("unknown".to_string()),
                ..Default::default()
            }
            .into(),
            ..Default::default()
        };
        let error = response_from_wire(&response_unknown_status)
            .expect_err("response mapping should reject unknown status enum value");
        assert!(matches!(error, KalanjiyamError::InvalidArgument(_)));

        let encoded = response_unknown_status.encode_to_vec();
        let view = wire::ResponseEnvelopeView::decode_view(&encoded)
            .expect("response view decode should succeed for malformed logical payload");
        let error = response_from_wire_view(&view)
            .expect_err("response view mapping should reject unknown status enum value");
        assert!(matches!(error, KalanjiyamError::InvalidArgument(_)));
    }

    #[test]
    fn stats_level_overflow_is_rejected() {
        let bad_stats_payload = wire::StatsResponse {
            observation_seqno: 1,
            data_generation: 2,
            levels: vec![wire::LevelStats {
                level_no: u32::from(u16::MAX) + 1,
                file_count: 1,
                logical_bytes: 2,
                physical_bytes: 3,
                ..Default::default()
            }],
            logical_shards: vec![wire::LogicalShardStats {
                start_bound: bound_to_wire(&Bound::NegInf).into(),
                end_bound: bound_to_wire(&Bound::PosInf).into(),
                live_size_bytes: 9,
                ..Default::default()
            }],
            ..Default::default()
        };

        let response = wire::ResponseEnvelope {
            client_id: "c5".to_string(),
            request_id: 8,
            status: status_to_wire(&Status::ok()).into(),
            payload: Some(wire::response_envelope::Payload::Stats(Box::new(
                bad_stats_payload,
            ))),
            ..Default::default()
        };

        let error = response_from_wire(&response)
            .expect_err("response mapping should reject level numbers above u16");
        assert!(matches!(error, KalanjiyamError::InvalidArgument(_)));

        let encoded = response.encode_to_vec();
        let view = wire::ResponseEnvelopeView::decode_view(&encoded)
            .expect("response view decode should succeed for malformed logical payload");
        let error = response_from_wire_view(&view)
            .expect_err("response view mapping should reject level numbers above u16");
        assert!(matches!(error, KalanjiyamError::InvalidArgument(_)));
    }

    #[test]
    fn missing_bound_kind_is_rejected() {
        let bad_bound = wire::Bound::default();
        let error =
            bound_from_wire(&bad_bound).expect_err("bound mapping should reject missing kind");
        assert!(matches!(error, KalanjiyamError::InvalidArgument(_)));

        let encoded = bad_bound.encode_to_vec();
        let view = wire::BoundView::decode_view(&encoded)
            .expect("bound view decode should succeed for malformed logical payload");
        let error =
            bound_from_wire_view(&view).expect_err("bound view mapping should reject missing kind");
        assert!(matches!(error, KalanjiyamError::InvalidArgument(_)));
    }
}
